import { StyleSheet } from "react-native";

export const colors = {
  background: "#11140F",
  accent: "#D8FF57",
  text: "#F2F4E9",
} as const;

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: colors.background },
  content: { padding: 18, paddingBottom: 52 },
  hero: { paddingVertical: 22, borderBottomWidth: 1, borderBottomColor: "#343A2E", marginBottom: 12 },
  eyebrow: { color: colors.accent, fontSize: 11, fontWeight: "800", letterSpacing: 2.2 },
  title: { color: colors.text, fontSize: 39, lineHeight: 42, fontWeight: "800", letterSpacing: -1.2, marginTop: 10 },
  subtitle: { color: "#A6AD98", fontSize: 15, lineHeight: 22, marginTop: 12, maxWidth: 520 },
  summary: { flexDirection: "row", gap: 10, marginVertical: 10 },
  testRow: { flexDirection: "row", alignItems: "center", paddingVertical: 18, borderBottomWidth: 1, borderBottomColor: "#2C3128" },
  testIndex: { color: "#6F7765", fontSize: 12, fontWeight: "700", width: 34 },
  testCopy: { flex: 1 },
  testTitle: { color: "#EEF1E5", fontSize: 18, fontWeight: "700" },
  testDescription: { color: "#8E9683", fontSize: 13, marginTop: 4 },
  arrow: { color: colors.accent, fontSize: 30, marginLeft: 12 },
  instructions: { backgroundColor: colors.accent, padding: 16, borderRadius: 4, marginBottom: 16 },
  instructionsLabel: { color: "#1B2016", fontSize: 10, fontWeight: "900", letterSpacing: 2 },
  instructionsText: { color: "#1B2016", fontSize: 15, lineHeight: 21, fontWeight: "600", marginTop: 6 },
  card: { backgroundColor: "#1A1F17", borderWidth: 1, borderColor: "#343A2E", borderRadius: 4, paddingHorizontal: 16, marginBottom: 14 },
  metric: { flex: 1, minWidth: 120, paddingVertical: 13, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: "#394033" },
  metricLabel: { color: "#899080", fontSize: 11, textTransform: "uppercase", letterSpacing: 1 },
  metricValue: { color: "#F1F3E9", fontSize: 17, fontWeight: "700", marginTop: 5 },
  good: { color: colors.accent },
  bad: { color: "#FF806B" },
  stateStage: { minHeight: 250, justifyContent: "center", alignItems: "center", borderRadius: 4, marginBottom: 14 },
  stateInserted: { backgroundColor: "#26351A" },
  stateDetached: { backgroundColor: "#38221D" },
  stateLabel: { color: "#AAB39C", fontSize: 11, fontWeight: "800", letterSpacing: 2 },
  stateValue: { color: "#F4F7E9", fontSize: 44, fontWeight: "800", letterSpacing: -1, marginTop: 8 },
  note: { color: "#929A88", fontSize: 13, lineHeight: 19 },
  hoverTarget: { height: 250, borderWidth: 1, borderColor: "#59624F", backgroundColor: "#171B15", alignItems: "center", justifyContent: "center", marginBottom: 14 },
  targetCross: { color: colors.accent, fontSize: 56, fontWeight: "200" },
  targetLabel: { color: "#8E9683", fontSize: 11, letterSpacing: 2, marginTop: 12 },
  drawingArea: { height: 390, backgroundColor: "#E9EDDF", borderRadius: 4, overflow: "hidden" },
  actions: { minHeight: 58, flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 12 },
  clearButton: { borderWidth: 1, borderColor: "#59624F", paddingHorizontal: 18, paddingVertical: 9, borderRadius: 3 },
  clearText: { color: colors.accent, fontWeight: "700" },
  buttonStage: { minHeight: 230, alignItems: "center", justifyContent: "center", backgroundColor: "#1A1F17", borderWidth: 1, borderColor: "#343A2E", marginBottom: 14 },
  buttonPressed: { backgroundColor: "#34421F", borderColor: colors.accent },
  motionStage: { minHeight: 250, backgroundColor: "#171B15", borderWidth: 1, borderColor: "#343A2E", alignItems: "center", justifyContent: "center", marginBottom: 14 },
  motionX: { color: colors.accent, fontSize: 45, fontWeight: "800", fontVariant: ["tabular-nums"] },
  motionDivider: { color: "#6F7765", fontSize: 10, letterSpacing: 2, marginVertical: 8 },
  motionY: { color: colors.text, fontSize: 45, fontWeight: "800", fontVariant: ["tabular-nums"] },
  empty: { color: "#899080", textAlign: "center", paddingVertical: 60 },
  eventRow: { paddingVertical: 13, borderBottomWidth: 1, borderBottomColor: "#2C3128" },
  eventName: { color: colors.accent, fontSize: 14, fontWeight: "700" },
  eventDetail: { color: "#9DA594", fontSize: 11, lineHeight: 16, marginTop: 5, fontFamily: "monospace" },
});
